### ISSUE TITLE
TGoogleSheetsOuput update

### ISSUE THREAD

**Issue by aeatthompson** [jlolling/talendcomp_tGoogleSheet#1]
I have been using this component and recently got an error 

>   "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Request payload size exceeds the limit: 10485760 bytes.",
    "reason" : "badRequest"
  } ],
  "message" : "Request payload size exceeds the limit: 10485760 bytes.",
  "status" : "INVALID_ARGUMENT"

After contacting Google support they said I was using update and should be using batchupdate in the sheets api.  Is this something the tGoogleSheetOutput component can be updated to do?  Or do I need to attempt to do this in a copy of the source?

Thanks for the amazing component

**Comment by jlolling** [comment]
I will check that.

**Comment by jlolling** [comment]
Indeed, the write method does not use the batch update API. I am going to change that.

**Comment by jlolling** [comment]
Could you give me an idea about the number of columns and rows you had in your request?
I know a limit of 2.000.000 cells per spreadsheet.

**Comment by jlolling** [comment]
I have just build a new release 3.1 which uses the batch update API.
Please give it a try and provide feedback.

**Comment by aeatthompson** [comment]
Sheet was 125k and moved to about 147k.  Use this to move student data into Google sheets for graphing.

I will try the new build and report back. Thank you.

**Comment by aeatthompson** [comment]
To test I move the old version folder out of my Talend custom component area and moved the folders for tGoogleSheetInput and tGoogleSheetOutput in than ran the job.  

I got the same error message about "Request payload size exceeds the limit: 10485760 bytes.",
Attached is the full text of error from Talend and a screenshot of Talend job

[error.txt](https://github.com/jlolling/talendcomp_tGoogleSheet/files/2090887/error.txt)
![2018-06-11 11_26_12](https://user-images.githubusercontent.com/40070563/41244440-a3908746-6d6a-11e8-896b-fd473528caca.png)

**Comment by jlolling** [comment]
OK, this gives us the hint, using the bulk api is not quite enough to solve the problem.
I guess I have to implement a kind of paging and send multiple different requests to lower the size of one request. This will take some time.
So far you can implement the paging also for your self by limiting the number of rows written within one sub job and restart with the next bunch of rows.
This is not the best way but if you are in a hurry - thats the current fastest way.

**Comment by aeatthompson** [comment]
Not currently in a hurry.  So just let me know when you need it tested.  Thanks

**Comment by aeatthompson** [comment]
I contacted Google support again and this is their response

> Apologies for the confusion. I meant to split the request in to batch requests, and then submit a subset at a time. Even when breaking a request in to batches, the 10 MB limit still applies for the over all request size, so submitting smaller batches, of less than 8-9 MB, allowing for batch overhead, should resolve the issue.

**Comment by jlolling** [comment]
Thanks for the reply. We now know we have to send multiple requests instead of one.
I will implement this feature in the next couple of weeks. Sorry, I have some other higher priorities currently.

**Comment by AndreaPaglia** [comment]
Hi, I'm struggling with the same problem. 
can I ask you an example of how would you implement the paging to limit the rows, using talend standard components? thanks for the great work

**Comment by jlolling** [comment]
Sorry for the delay. I am now able to work on it.

**Comment by jlolling** [comment]
The component uses batch-update now. Please check it again with the current version.
Which version of the component you are running is visible in the advanced settings of the component.

**Comment by aeatthompson** [comment]
I show Release 3.0 build 20180609

I downloaded the zip for this repo and extracted the talend_component folder and put those into my custom component folder.  I did notice the date/time stamps on the files in there are still last years but you made some commits in other folders.
