### ISSUE TITLE
Unable to see the component in studio

### ISSUE THREAD

**Issue by eozturkTF** [jlolling/talendcomp_tGoogleSheet#10]
Hello,

Not sure this is the right place to post this, but i am unable to get the component in my Studio.
I am using TOS 7.3.1
I follow the procedure here : https://help.talend.com/r/en-US/7.3/install-update-custom-compt
And despite this, the component does not show up in the palette.

What am i missing ?

regards

**Comment by jlolling** [comment]
Please check if you can find the component in the folder: <studio-root>/plugins/org.talend.designer.components.localprovider_7.3.1.20200213_1003/components/ext/user/
If this is the case plase check if you can see the generated code here:
<your-workspace>/.JETEmitters/src/org/talend/designer/codegen/translators/cloud/google/tGoogleSheet*.java

BTW. The link you have provided does not work.
