### ISSUE TITLE
Empty sheet before writing

### ISSUE THREAD

**Issue by somersst** [jlolling/talendcomp_tGoogleSheet#11]
Hi,

I am using a tGoogleSheetOutput to write data to a certain tab in a sheet.
Unfortunateley it doesn't empty the existing tab before writing to. So when the next time there are less results, the latest old entries still remain in the sheet...

**Comment by jlolling** [comment]
Thats right. I will check if the API allow cleanup sheets

**Comment by jlolling** [comment]
Please try the option "Delete rows after last written row".
In such use case please start writing at the start row. All values will be overwritten and the rows not affected by your new output will be deleted this way.

**Comment by jlolling** [comment]
Nevertheless I am currently implementing the function to clear the sheet for the expected column range.

**Comment by jlolling** [comment]
I have just implemented the option "Remove all rows in this sheet before writing"
