### ISSUE TITLE
How to read the number with out comma 8,215,434 in number.

### ISSUE THREAD

**Issue by gurusewack** [jlolling/talendcomp_tGoogleSheet#18]
I have read data from a Google Sheet with the datatype as String, but the numbers are in comma format. Please help me resolve this issue without commas.

Example: 8,215,434

This is the production issue of my project.

**Comment by jlolling** [comment]
This is the current default behaviour rendering numbers as String. You can better read the number as Long typed values and convert in a tMap into a String with String.valueOf(your_long_value).
I am currently working the component to improve the error handling for authorization problems.
I also change the number to String conversion and remove the grouping (thats what you are currently complaining).

**Comment by jlolling** [comment]
This problem is solved. Please download the new release (v6.0) in the Release section: https://github.com/jlolling/talendcomp_tGoogleSheet/releases

**Comment by jlolling** [comment]
Done

**Comment by jlolling** [comment]
Please download the release 6.1!

**Comment by gurusewack** [comment]
Thanks Jan I will download test it.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
