### ISSUE TITLE
Talend component not showing up

### ISSUE THREAD

**Issue by bakembo01** [jlolling/talendcomp_tGoogleSheet#20]
I tried to install the component via maven and also manually adding the folder inside the components folder in my Talend installation directory but I can't see the tGoogleSheet components in the palette tab.
Do you have any suggestions please?
thank you

**Comment by jlolling** [comment]
You do not have to install them via maven. The maven build creates the components and copies them into a pre-configured custom component folder which have to be also configured in the studio.
BUT:
The ready to use components are available in the Releases section of this Github repo: https://github.com/jlolling/talendcomp_tGoogleSheet/releases
Copy and unpack this zip file in your custom component folder (check the folder in the studio in Preferences->Talend->Component).

**Comment by jlolling** [comment]
Here a help page for installing custom components: https://jan-lolling.de/

**Comment by bakembo01** [comment]
thank you very much it worked

**Comment by jlolling** [comment]
You welcome.
