### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by dorel14** [jlolling/talendcomp_tGoogleSheet#5]
Hello 
First Thx for this component

When i run , i have this error in logs

`AVERTISSEMENT: Unable to set permissions for C:\Talend\workspace\AKUITEO_OUTILS\googleApi\334511680046-rt44hoid6p1d41o2hoihhcpjvg8d41p0.apps.googleusercontent.com, because you are running on a non-POSIX file system.`

Do you knox why and how i can fix it ?

**Comment by jlolling** [comment]
On which system and filesystem do you run the job?
The component creates a folder and tries to set exclusive read rights for the folder of the current user.
This is a functionality of the Google API implementation and I cannot change that.

Best regards
Jan Lolling

**Comment by dorel14** [comment]
Windows 10 pro

**Comment by jlolling** [comment]
Ok in this case set manually the rights to this folder exclusively to the user running this job (you).


Jan Lolling
