### ISSUE TITLE
Exception in component tGoogleSheetOutput_2

### ISSUE THREAD

**Issue by lissianski** [jlolling/talendcomp_tGoogleSheet#6]
Hello!

I get this when I try to run a job that uses tGoogleSheetOutput:

Starting job gc_orders at 11:57 27/01/2021.
[statistics] connecting to socket on port 4062
[statistics] connected
Exception in component tGoogleSheetOutput_2 (gc_orders)
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:35)
	at com.google.api.client.googleapis.auth.oauth2.GoogleClientSecrets.getDetails(GoogleClientSecrets.java:82)
	at de.jlo.talendcomp.google.sheet.GoogleSheet.authorizeWithClientSecret(GoogleSheet.java:157)
	at de.jlo.talendcomp.google.sheet.GoogleSheet.initializeClient(GoogleSheet.java:204)
	at sam_poliglot.gc_orders_0_1.gc_orders.tFileInputExcel_1Process(gc_orders.java:2587)
	at sam_poliglot.gc_orders_0_1.gc_orders.runJobInTOS(gc_orders.java:4460)
	at sam_poliglot.gc_orders_0_1.gc_orders.main(gc_orders.java:4309)
[statistics] disconnected

Job gc_orders ended at 11:57 27/01/2021. [Exit code  = 1]

Here is the screenshot: http://joxi.ru/L21Xaa8t0QX38m

Here is how it is configured: http://joxi.ru/J2bDGGnHVD8b7r

I am quite new to Talend, so, no idea what may be wrong here.

Please, help.

Thanks in advance!

**Comment by jlolling** [comment]
Hi,

I am going to improve the error message. Could you please tell me the Talend version, the Java version and the version of the component (refer to the advanced settings of the component, here you can get the release info).

Best regards
Jan Lolling

**Comment by lissianski** [comment]
Jan,

it is Talend Open Studio for Data Integration for MacOS Version: 7.3.1

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

Here is what I got for the component: http://joxi.ru/zANaLLNFjG6j82

Thanks for helping me!

Regards,
Konstantin

**Comment by jlolling** [comment]
I have just release the new version with the more readable error message. Please checkout this version and tell me what you get.
Thanks
Best regards
Jan

**Comment by lissianski** [comment]
I have downloaded the new version. But it still shows the same version in the component. I am very new to Talend. What should I do to update it? Sorry for basic questions, but this is, really my first attempt to work with Talend.

Thanks!

**Comment by lissianski** [comment]
I restarted Talend Studion, but it did not work... Still the same version of the component in the Job.

**Comment by lissianski** [comment]
Hello Jan,

I managed to configure it right. It was all about configuring everything in Google and not about the component itself. So, I am closing this.

Thanks for answering me in the first place.

And good luck!

Regards,
Konstantin

**Comment by jlolling** [comment]
Thanks for notifying me. The purpose of the change was to provide an error message that point to the actual issue - the wrong type of credentials.
I have not published the new version to Talend Exchange, only here as new release.
I will publish it now to Talend Exchange and perhaps it is easier for you to get it.

**Comment by jlolling** [comment]
I tried to follow the download link you have provided. I did not get any useful information from it. Please use only the Github releases or Talend Exchange, nothing else please.

**Comment by jlolling** [comment]
I have just released the new version in Talend Exchange.
