### ISSUE TITLE
Feature request  Append value to sheet

### ISSUE THREAD

**Issue by dorel14** [jlolling/talendcomp_tGoogleSheet#7]
Hello , 
i have a weekly reporting to make in a google sheet , and have to write values at the last row 
I have seen that google api can do that with the append command

[spreadsheets.values.append](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/append)

It would be great having this in your component .

Thx

**Comment by jlolling** [comment]
It is done since version 5.0
